version: '3.1'

services:
  db:
    container_name: db
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3306
    ports: 
      - "3306:3306"
    volumes:
      - ./sample_data:/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  post_setup:
    container_name: setup_db
    image: mysql:latest
    depends_on:
      db:
        condition: service_healthy
    command: bash -c 'cd /data/employee && mysql -h db -uroot -p"root" < employees.sql; mysql -h db -uroot -p"root" < employees_partitioned.sql;'
    volumes:
      - ./sample_data:/data